[build]
  publish = "_site"
  command = "npm run build"

# Redirect any URLs with the language code in them already
/es/*   /:splat     301!

# Important: Per shadowing rules, URLs for the
# _non-default_ language-specific content files
# are served without redirects.

# Redirect for end-user’s browser preference override
/*      /en/:splat  302   Language=en
/*      /pt-br/:splat  302   Language=pt-br
/*      /es/:splat  200